<a href="https://colab.research.google.com/github/srradhakrishnan/ace/blob/master/EquiwidthBinning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import math
#equal frequency 
def equifreq(arr1, m): 
	
	a = len(arr1) 
	n = int(a / m) 
	for i in range(0, m): 
		arr = [] 
		for j in range(i * n, (i + 1) * n): 
			if j >= a: 
				break
			arr = arr + [arr1[j]] 
		print(arr) 

#equal width 
def equiwidth(arr1, m): 
	a = len(arr1) 
	w = int((max(arr1) - min(arr1)) / m) 
	min1 = min(arr1) 
	arr = [] 
	for i in range(0, m + 1): 
		arr = arr + [min1 + w * i] 
	arri=[] 
	
	for i in range(0, m): 
		temp = [] 
		for j in arr1: 
			if j > arr[i] and j < arr[i+1]: 
				temp += [j] 
		arri += [temp] 
	print(arri) 

#data to be binned 
data = [13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70] 
#no of bins 
m = 3
n=int(len(data)/m)
data=np.sort(data)
print("equal frequency binning") 
equifreq(data, m) 
b=data
print("\n\nequal width binning") 
equiwidth(data, m)

# create bins 
bin1=np.zeros((n,m))  
bin2=np.zeros((n,m)) 
bin3=np.zeros((n,m)) 

# Bin mean 
for i in range (0,n*m,m): 
    k=int(i/m)
    for j in range(m): 
      mean=mean+b[i+j]
    mean=mean/m
    for j in range(m): 
        bin1[k,j]=mean 
print("Bin Mean: \n",bin1) 
     
# Bin boundaries 
for i in range (0,n*m,m): 
    k=int(i/m) 
    for j in range (m): 
        if (b[i+j]-b[i]) < (b[i+m-1]-b[i+j]): 
            bin2[k,j]=b[i] 
        else: 
            bin2[k,j]=b[i+m-1]        
print("Bin Boundaries: \n",bin2) 
  
# Bin median 
for i in range (0,n*m,m): 
    k=int(i/m) 
    for j in range (m): 
        bin3[k,j]=b[i+math.floor(m/2)] 
print("Bin Median: \n",bin3) 



equal frequency binning
[13, 15, 16, 16, 19, 20, 20, 21, 22]
[22, 25, 25, 25, 25, 30, 33, 33, 35]
[35, 35, 35, 36, 40, 45, 46, 52, 70]


equal width binning
[[15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30], [33, 33, 35, 35, 35, 35, 36, 40, 45, 46], [52]]
Bin Mean: 
 [[79.68749857 79.68749857 79.68749857]
 [44.89583286 44.89583286 44.89583286]
 [35.96527762 35.96527762 35.96527762]
 [35.98842587 35.98842587 35.98842587]
 [38.66280862 38.66280862 38.66280862]
 [46.55426954 46.55426954 46.55426954]
 [50.51808985 50.51808985 50.51808985]
 [57.17269662 57.17269662 57.17269662]
 [75.05756554 75.05756554 75.05756554]]
Bin Boundaries: 
 [[13. 16. 16.]
 [16. 20. 20.]
 [20. 22. 22.]
 [22. 25. 25.]
 [25. 25. 30.]
 [33. 33. 35.]
 [35. 35. 35.]
 [36. 36. 45.]
 [46. 46. 70.]]
Bin Median: 
 [[15. 15. 15.]
 [19. 19. 19.]
 [21. 21. 21.]
 [25. 25. 25.]
 [25. 25. 25.]
 [33. 33. 33.]
 [35. 35. 35.]
 [40. 40. 40.]
 [52. 52. 52.]]
